#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Author: Yonglin Wang
# Date: 2021/1/29
"""Constants used in scripts. Crucially, to prevent circular import, this script does not import relative modules."""

from collections import OrderedDict

RANDOM_SEED = 2020

# -----
# Feature extraction Constants
# -----
# names to save each column under, original data if no "calculated" or "normalized" specified in file path
# In principle,if the directory is not tampered, the following arrays should all have shape (n, [sampling_rate])
COL_PATHS = OrderedDict({"velocity": "velocity.npy",  # training, (n_sample, sampling_rate)
                         "velocity_cal": "velocity_calculated.npy",  # training, (n_sample, sampling_rate)
                         "position": "position.npy",  # training, (n_sample, sampling_rate)
                         "joystick": "joystick_deflection.npy",  # training, (n_sample, sampling_rate)
                         "destabilizing": "destabilizing_deflection.npy",  # training, (n_sample, sampling_rate)
                         "trial_key": "corresponding_peopleTrialKey.npy",  # for output reference only (n_samples,)
                         "start_seconds": "entry_start_seconds.npy",  # can be added as feature?  (n_samples.)
                         "end_seconds": "entry_end_seconds.npy",  # can be added as feature?  (n_samples,)
                         "label": "label.npy",  # truth label. 1=crash, 0=noncrash (n_sample,)
                         })

# lists of initial feature columns generated by generate_feature_files
INIT_FEATURES = {"velocity", "velocity_cal", "position", "joystick", "trial_key", "start_seconds", "end_seconds", "label"}

# argparser value checker
MIN_STEP = 0.04

# crash event criteria
MIN_ENTRIES_IN_WINDOW = 2  # minimum # of entries between two crash events (i.e. in a window)

# paths for saving output
DEBUG_FORMAT = "debug_{}ahead_{}window.csv"

# columns we will use for interpolation
COLS_TO_INTERPOLATE = ('currentVelRoll', 'currentPosRoll', 'calculated_vel', 'joystickX')

# -----
# DataLoader Constants
# -----

# velocity mode tag
CALCULATED = "calc"
ORIGINAL = "orig"

# paths for saving output
DATA_OUT_DIR_FORMAT = "data/{}window_{}ahead_{}rolling/"
EXP_OUT_DIR_FORMAT = "exp/{}window_{}ahead_{}rolling/"

# path to pickle dataloader, saved under expriment
LOADER_BASENAME = "dataloader.pkl"

# Unique IDs for X Y data preprocessing configuration
CONFIG_IDS = {1, 2, 3}

# train test split config constants
TEST_SIZE = 0.2
USED_COL_FORMAT = "{}_InTrain"

# configuration specific details
CONFIG_1_2_SPECS = {"y_enc_path": "config1_y_enc.pkl"}

# -----
# Model Constants
# -----

# list of available models
AVAILABLE_MODELS = ["lstm"]

# path to save model (to be joined with


